### ISSUE TITLE
Issues regarding the Hybrid Graphics switching

### ISSUE THREAD

**Issue by vanwijkdave** [t2linux/wiki#311]
Hi all, got an issue regarding the Hybrid Graphics switching

**Device and general info:**
- 16 inch 2019 MacBook Pro, pretty baseline except the 32GB RAM upgrade.
- Got ubuntu installed and its running 22.0.4. 
- Using ReFind for booting and Ubuntu install which boots using GRUB

**Issue**
Basically there are two issues which might be linked together:

-My Ubuntu install isn't able to switch to the GPU using the `gpu-switch -i` command. `glxinfo | grep "OpenGL renderer`  just outputs the AMD card. However the system does recognise the internal graphics when running `lspci -s 00:02.0`. 

-When booting into MacOS using ReFind - after using Ubuntu with the custom graphics- resuming from sleep leaves the device with a black screen, everything works (can see the programs I open using spotlight via my Touch Bar) but the screen is just black.  This issue doesn't appear when booting MacOS via the default Bootmanager.

**Other Info**
When first setting up hybrid graphics with this guide: https://wiki.t2linux.org/guides/hybrid-graphics/ it seemed to work. I started noticing the issue only after I booted into MacOS and everything fell apart.

Hope someone might be able to help with this one, thanks!

**Comment by Redecorating** [comment]
Hi,

> My Ubuntu install isn't able to switch to the GPU using the gpu-switch -i command. glxinfo | grep "OpenGL renderer just outputs the AMD card.

Did you reboot after running gpu-switch and before glxinfo? When you boot to macos, gpu-switch gets reset back to the amdgpu. Make sure you reboot after using `gpu-switch -i`, it only takes effect after a reboot.

> resuming from sleep leaves the device with a black screen

To avoid this, can you try making sure you run `gpu-switch -d` in linux before booting macos, as macos is meant to have the dgpu active at boot (it knows how to switch at runtime)

> This issue doesn't appear when booting MacOS via the default Bootmanager.

Would this be the second time in a row of booting macos? If so, gpu switch will have been reset by macos so the second boot wouldn't have the issue.

> only after I booted into MacOS and everything fell apart.

Yep that'll be because macOS resets gpu-switch whenever you boot it.

**Comment by vanwijkdave** [comment]
Thanks, this clarifies a lot. The intel graphics are indeed working after a reboot, and MacOS works fine if switched to dedicated before rebooting.

I'll add a PR with a notice of this to the wiki, might save a few future users some headaches :)
